import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'Confirm Logout': 'Confirm Logout',
      'Are you sure you want to log out?': 'Are you sure you want to log out?',
      'Cancel': 'Cancel',
      'Log Out': 'Log Out',
      'articles': 'articles',
      'Hello': 'Hello',
      'Extras': 'Extras',
      'HOME': 'HOME',
      'Login': 'Login',
      'Acount Center': 'Acount Center',
      'Search': 'Search',
      'Sign up': 'Sign up',
      'username': 'Username',
      'password': 'Password',
      'enter_otp': 'Enter OTP',
      'verify_otp': 'Verify OTP',
      'login_successful': 'Logged in successfully!',
      'otp_invalid': 'Invalid OTP, please try again.',
      'Invalid OTP, please try again.':'Invalid OTP, please try again.',
      'error': 'Error',
      'enter_credentials': 'Please enter your credentials.',
      'invalid_otp': 'Invalid OTP format.',
      'My Cars': 'My Cars',
      'Favorites': 'Favorites',
      'Home': 'Home',
      'Settings': 'Settings',
      'Shop': 'Shop',
      'Map': 'Map',
      'Work': 'Work',
      'Travel': 'Travel',
      'Garage': 'Garage',
      'Contact': 'Contact',
      'Search Page': 'Search Page',
      'Notifications Page': 'Notifications Page',
      'Profile Page': 'Profile Page',
      'Page Not Found': 'Page Not Found',
      'ECU': 'ECU',
      'PARS': 'PARS',
      'Profile': 'Profile',
      'account Center': 'account Center',
      'Manage your connected account, add or integrate': 'Manage your connected account, add or integrate',
      'This is the test text from ECUPars': 'This is the test text from ECUPars',
      'This app is improving constantly.': 'This app is improving constantly.',
      'test user': 'Test User',
      'Your Product': 'Your Product',
      'Product info': 'Product Information',
      'Invite Section': 'Invite Section',
      'Your invite code': 'Your Invite Code',
      'About App': 'About App',
      'Share App': 'Share App',
      'Contact Support': 'Contact Support',
      'account': 'account',
      'Invitation': 'Invitation',
      'Agreement': 'Agreement',
      'Private Policy': 'Privacy Policy',
      'Ver 0.0.0.1': 'Version 0.0.0.1',
      'Application Theme': 'Application Theme',
      'Light': 'Light',
      'Dark': 'Dark',
      'Application Language': 'Application Language',
      'Language:': 'Language:',
      'Application Preference': 'Application Preference',
      'This section is on development': 'This section is under development',
      'Recommend ECU Pars to friends': 'Recommend ECU Pars to friends',
      'nearby without Internet.': 'nearby without Internet.',
      'QR code': 'QR code',
      'Open URL': 'Open URL',
      'Share Via': 'Share Via',
      'Qr Code': 'Qr Code',
      'URL': 'URL',
      'Facebook': 'Facebook',
      'More': 'More',
      'Logout from your account': 'Logout from your account',
      'Log out': 'Log out',
      'Information': 'Information',
      'Application version': 'Application version',
      'Application developer': 'Application developer',
      'Application on store': 'Application on store',
      'View on Google Play': 'View on Google Play',
      'Description': 'Description',
      'No Internet Connection': 'No Internet Connection',
      'Please check your connection and try again.': 'Please check your connection and try again.',
      'Connected': 'Connected',
      'You are now connected to the internet!': 'You are now connected to the internet!',
      'Checking internet connection...': 'Checking internet connection...',
      'Connected to the internet!': 'Connected to the internet!',
      'Related Categories': 'Related Categories',
      'Issues': 'Issues',
      'Main Categories': 'Main Categories',
      'Sub Category': 'Sub Category',
      'Are you sure?': 'Are you sure?',
      'Do you really want to go back to the home screen?': 'Do you really want to go back to the home screen?',
      'GET': 'GET',
      'Link is copied!': 'Link is copied!',
      'Please put your OTP code for continue.': 'Please put your OTP code for continue.',
      'PRO': 'PRO',
      'ACCESS': 'ACCESS',
      'UNLIMITED': 'UNLIMITED',
      'Searching contents': 'Searching contents',
      'Your subscription auto-renews weekly unless canceled.': 'Your subscription auto-renews weekly unless canceled.',
      'Subscription are managed via your Google Play Billing and will renew': 'Subscription are managed via your Google Play Billing and will renew',
      'Terms of use': 'Terms of use',
      'Privacy policy': 'Privacy policy',
      'Error': 'Error',
       "All": "All",
      'Solutions': 'Solutions',
      "Articles": "Articles",
       "Saved": "Saved",
       'Errors': 'Errors',
      "Failed to receive OTP":"Failed to receive OTP",
       'Maps': 'Maps',
       'ارسال مجدد': 'Resend code',
       'Version': 'Version',
       'Invalid username or password.': 'Invalid username or password.',
      'No subcategories available':'No subcategories available',
      'Unnamed Subcategory':'Unnamed Subcategory',
      'Filter results':'Filter results',
      'Apply':'Apply',
      'General Searching':'General Searching',
      'Yes':'Yes',
      'مشکلی در بارگیری اطلاعات رخ داده است. لطفاً دوباره تلاش کنید.':'There is have been a problem to fetching data.Please try again.',
       'Steps': 'Steps',
      'Search...': 'Search...',
      'Error loading step details': 'Error loading step details',
      'Load More':'Load More',
      'Unload all the features\nwith the Pro version':'Unload all the features\nwith the Pro version',
      'Please select a plan': 'Please select a plan',
      'Subscribe': 'Subscribe',
      'Account Center': 'Account Center',
      'About APP':'About APP',
      'Your Referral Code': 'Your Referral Code',
      'Referral':'Referral',
      'Your Discounts Code': 'Your Discounts Code',
      'No invitees available.':'No invitees available.',
  'Data is updated!' : 'Data is updated!',
      'Contact  Support': 'Contact  Support',
      'دسترسی محدود': 'Access is limited',
      'خطا': 'Error',
      'No title': 'No title',
      'حساب کاربری شما قبلاً ایجاد شده است. لطفاً برای ادامه، از گزینه ورود استفاده کنید.' : 'Your account has been created. please for continue use login method.',
      'Have a great time!' : 'Have a great time!',
    },
    'fa': {
      'مشکلی در بارگیری اطلاعات رخ داده است. لطفاً دوباره تلاش کنید.':'مشکلی در بارگیری اطلاعات رخ داده است. لطفاً دوباره تلاش کنید.',
      'برای دسترسی به این بخش، لطفاً سطح کاربری خود را ارتقا دهید.':'برای دسترسی به این بخش، لطفاً سطح کاربری خود را ارتقا دهید.',

      'Unload all the features             \nwith the Pro version':'تمام ویژگی ها را                  \n         با نسخه ویژه باز کنید',
      'Private Policy': 'حریم خصوصی کاربران',
      'Earn 3 doller now!':'با معرفی دوستان‌تان، در این مسیر ارزشمند سهیم باشید.',
      'No invitees available.':'هیچ شخصی یافت نشد',
      'Articles': 'مقاله ها',
      'Invalid OTP, please try again.':'رمز دو مرحله ایی شما اشتباه است.',
      'Solutions': 'راهکار ها',
      'No description': 'بدون شرح',
      'No title': 'بدون عنوان',
      'Failed to receive OTP': 'خطا در دریافت کد دو مرحله ایی',
      'Invite a friend with the options': 'دوست خود را با روش های زیر دعوت کنید.',
      'About APP':'درباره برنامه',
      'below. You both earn easy money.':'فرصتی برای تجربه‌ی یک همکاری پربار در کنار ما منتظر شماست.',
      'All' : 'همه',
      'Link is copied!' : 'لینک کپی شد!',
      'A new OTP has been sent to' : 'کد دو مرحله ایی برای شما ارسال گردید.',
      'Error in resending otp.' : 'خطا در ارسال مجدد کد دو مرحله ایی',
      'Error' : 'خطا',
      'Error in login please try again.' : 'خطا در انجام عملیات لطفا دوباره تلاش کنید.',
      'Invalid username or password.' : 'نام کاربری یا پسورد شما اشتباه است.',
      'All fields are required' : 'لطفا فیلد های ضروری را به دقت پر کنید.',
      'Removing...' : 'در حال حذف..',
      'Please put your OTP code for continue.' : 'کد دو مرحله ایی برای شما ارسال گردید.',
      'Sign Up' : 'ثبت نام',
      'Next' : 'بعدی',
      'Scan ECU Pars to get discount!' : 'برای اشتراک گذاری کد را اسکن کنید!',
      'Cancel' : 'لغو',
      '.Invalid username or password' : 'نام کاربری یا پسورد شما اشتباه است.',
      'No Title' : 'بدون عنوان',
      'benz':'بنز',
      'Error loading step details':'خطا در بارگزاری مراحل',
      'PRO  ':' ویژه',
      'No saved items yet':'هیچ ایتم ذخیره شده ایی موجود نیست',
      'ACCESS ':' به سطح',
      'GET  ':'دست‌یابی',
      'OTP sent successfully':'کد دو مرحله ایی با موفقعیت ارسال شد.',
      'volvo':'ولوو',
      'A new OTP has been sent to you':'کد دو مرحله ایی جدیدی برای شما ارسال گردید',
      'scania': 'اسکانیا',
      'OTP Resent': 'کد دو مرحله ایی ارسال شد',
      'daf':'داف',
      'No subscriptions available.':'هیچ اشتراکی وجود ندارد.',
      'step_not_found':'مرحله یا راهکار مورد نظر پیدا نشد',
      'Success':'ارسال شد!',
      'login_required':'برای دسترسی به این مرحله باید دوباره وارد شوید.',
      'OTP Sent':'کد دو مرحله ایی ارسال شد',
      'An error occurred while sending OTP':'مشکلی در ارسال کد دومرحله ایی بوجود امده',
      'man': 'مان',
      'no_active_subscription': 'هیچ اشتراک فعالی ندارید.',
      'subscription_inactive': '"اشتراک شما غیرفعال است',
      'category_access_restricted': 'دسترسی به این دسته محدود شده است',
      'No articles found': 'هیچ مقاله ایی پیدا نشد.',
      'City (non required)': 'شهر (غیر ضروری)',
      'Car Brand (required)': '(ضروری) برند ماشین',
      'renault': 'رنو',
      'foton' : 'فوتون',
      'map_access_denied' : 'دسترسی به نقشه‌ها مجاز نیست',
      'jac': 'جک',
      'unknown_error': 'خطای نامشخصی رخ داده لطفا دوباره تلاش  کنید.',
      'issues_access_denied': 'جک',
      'Confirm Phone Number': 'شماره تلفن خود را وارد کنید',
      'iveco': 'اویکو',
      'Login Error': 'خطا در احراز هویت',
      'Login Failed': 'احراز هویت انجام نشد',
      'Referrer Code (Optional)': 'کد معرفی(غیر ضروری)',
      'cummins': 'کامینز',
      'دسترسی محدود': 'دسترسی محدود',
      'other':'سایر موارد',
      'Days remaining :':'روز های باقی مانده',
      'Loading...' : 'در حال بارگزاری...',
      'Last name' : 'نام خانوادگی',
      'First name' : 'نام',
      'Website' : 'وبسایت',
      'Email' : 'ایمیل',
      'Are you have a discount code?' : 'کد تخفیف دارین؟',
      'Enter your discount code' : 'کد تخفیف را وارد کنید',
      'No Image Available' : 'هیچ نقشه ایی موجود نیست.',
      'Verify OTP' : 'اعتبارسنجی کد',
      'Enter Password' : 'پسورد خود را وارد کنید.',
      'Enter OTP Code' : 'کد ارسال شده را وارد کنید',
      'Enter otp' : 'تایید کد دو مرحله ایی',
      'Telegram' : 'تلگرام',
      'حساب کاربری شما قبلاً ایجاد شده است. لطفاً برای ادامه، از گزینه ورود استفاده کنید.' : 'حساب کاربری شما قبلاً ایجاد شده است. لطفاً برای ادامه، از گزینه ورود استفاده کنید.',
      'Instagram' : 'اینستاگرام',
      'QR Code' : 'QR کد',
      'Scan EcuPars to get discount!' : 'کد زیر را اسکن کنید و برند شوید!',
      'Referral Link' : 'لینک معرفی',
      'Invitees' : 'دعوت شدگان',
      'Your referral code' : 'کد دعوت شما',
      'Get' : 'برو',
      'Data is updated!' : 'اطلاعات بروز شد!',
      'Have a great time!' : 'اوقات خوبی داشته باشید!',
      "Errors": "خطا ها",
      "Maps" : "نقشه ها ",
      "Steps": "مراحل",
      'Saved': 'ذخیره شده',
      'Terms of use': 'شرایط استفاده',
      'Privacy policy': 'سیاست حفظ حریم خصوصی',
      'Load More':'بیشتر',
      'Search...':'جستجو...',
      'Error': 'خطا',
      'Please select a plan': 'لطفا یک طرح انتخاب کنید',
      'Subscribe': 'اشتراک',
      'GET': 'دریافت',
      'PRO': 'حرفه‌ای',
      'UNLIMITED': 'نامحدود',
      'Searching contents': 'جستجوی محتوا',
      'Your subscription auto-renews weekly unless canceled.': 'همه اشتراک‌ها سالانه هستند و هزینه تمدید برای تمامی کاربران، معادل هزینه اشتراک برنزی خواهد بود.',
      'Subscription are managed via your Google Play Billing and will renew': 'اشتراک‌ها از طریق صورتحساب Google Play شما مدیریت می‌شوند و تمدید خواهند شد.',
      'View': 'مشاهده',
      'Yes' : 'بله',
      'Related Categories': 'دسته‌های مرتبط',
      'Filter results': 'فیلتر نتایج',
      'Apply': 'تایید',
      'No invitees available': 'هیچ دعوت شده ایی موجود نیست.',
      'No subcategories available': 'هیچ زیر دسته ایی یافت نشد',
      'Unnamed Category': 'دسته ناشناس',
      'General Searching': 'همه',
      'Issues': 'خطا ها',
      'Contact  Support': 'پشتیبانی',
      'Main Categories': 'دسته‌بندی‌های اصلی',
      'Sub Category': 'زیر دسته‌بندی',
      'You will be logged out of your account.': 'شما از اکانت خود خارج خواهید شد.',
      'Are you sure?': 'آیا مطمئن هستید؟',
      'Do you really want to go back to the home screen?': 'آیا واقعاً قصد بازگشت به صفحه اصلی را دارید؟',
      'Log out': 'خروج',
      'Logout from your account': 'خروج از حساب کاربری',
      'articles': 'مقاله ها',
      'Account Center': 'مدیریت حساب کاربری',
      'Your Referral Code': 'کد معرفی شما',
      'Your Discounts Code': 'کد تخفیف شما',
      'Product    Information': 'اطلاعات  محصول',
      "User ID": "شماره کاربری",
      "Username": "نام کاربری",
      "Your Discount code" : "",
      "Referral" : "کد معرفی",
      "First Name": "اسم",
      "Last Name" : "فامیل",
      "Phone Number" : "شماره تماس",
      "City": "شهر",
      "Job":"شغل",
      "National ID": "کد ملی",
      'Hello': 'سلام',
      'Extras': 'کاربردی',
      'HOME': 'خانه',
      'Login': 'ورود',
      'Search': 'کاوش',
      'Sign up': 'ثبت نام',
      'username': 'نام کاربری',
      'password': 'رمز عبور',
      'enter_otp': 'کد ارسال شده را تایید کنید',
      'verify_otp': 'تایید کد بک بار مصرف',
      'login_successful': 'ورود موفقیت آمیز',
      'otp_invalid': 'کد یکبار مصرف نامعتبر',
      'error': 'خطا',
      'enter_credentials': 'خطا اعتبارسنجی',
      'invalid_otp': 'کد اعتبارسنجی نامعتبر',
      'My Cars': 'ماشین‌های من',
      'Favorites': 'موارد دلخواه',
      'Home': 'خانه',
      'Settings': 'تنظیمات',
      'Shop': 'فروشگاه',
      'Map': 'نقشه',
      'Work': 'کار',
      'Travel': 'سفر',
      'Garage': 'گاراژ',
      'Contact': 'تماس',
      'Search Page': 'صفحه جستجو',
      'Notifications Page': 'صفحه اطلاعیه‌ها',
      'Profile Page': 'صفحه پروفایل',
      'Page Not Found': 'صفحه پیدا نشد',
      'ECU': 'ECU',
      'PARS': 'PARS',
      'Profile': 'پروفایل',
      'Acount Center': 'مرکز حساب',
      'Manage your connected account, add or integrate': 'حساب‌ متصل خود را مدیریت کنید',
      'This is the test text from ECUPars': 'این یک متن آزمایشی از ECUPars است',
      'This app is improving constantly.': 'این برنامه دائما در حال بهبود است.',
      'test user': 'کاربر آزمایشی',
      'Your Product': 'محصول شما',
      'Product info': 'اطلاعات محصول',
      'Invite Section': 'بخش دعوت',
      'Your invite code': 'کد دعوت شما',
      'About App': 'درباره برنامه',
      'Share App': 'اشتراک‌گذاری برنامه',
      'Contact Support': 'پشتیبانی تماس',
      'account': 'حساب کاربری',
      'Invitation': 'دعوت‌نامه',
      'Data is loading, please wait.': 'اطلاعات در حال بروزرسانی هستند..',
      'Please wait...': 'لطفا صبر کنید...',
      'Agreement': 'توافق‌نامه',
      'Version': 'نسخه',
      'Application Theme': 'تم برنامه',
      'Light': 'روشن',
      'No Discount Code': 'هیچ کد تخفیفی موجود نیست.',
      'You have it until: ': 'شما این کد تخفیف را تا ',
      'Discount code copied!': 'کد تخفیف کپی شد!',
      'Your Discount code:': 'کد تخفیف شما',
      'Discounts': 'تخفیف ها',
      'You dont have a discount code.': 'شما کد تخفیفی جهت استفاده ندارید.',
      'Otp': 'کد دو مرحله ایی',
      'Enter OTP': 'کد دو مرحله ای',
      'Dark': 'تاریک',
      'Usage Remaining:': 'مانده',
      'Invite a friend with the options to get extra gifts.': 'دوستتان را دعوت کنید تا هدایای بیشتری کسب کنید.',
      'You have': 'شما دارای',
      '% Discount Code!': '% کد تخفیف هستین!',
      'Application Language': 'زبان برنامه',
      'Language:': 'زبان:',
      'Application Preference': 'ترجیح برنامه',
      'This section is on development': 'این بخش در حال توسعه است',
      'Recommend ECU Pars to friends': 'ECU Pars را به دوستانتان معرفی کنید',
      'nearby without Internet.': 'بدون نیاز به اینترنت در نزدیکی.',
      'QR code': 'کد QR',
      'Open URL': 'باز کردن لینک',
      'Share Via': 'اشتراک‌گذاری از طریق',
      'Qr Code': 'کد QR',
      'URL': 'لینک',
      'Facebook': 'فیس‌بوک',
      'More': 'بیشتر',
      'Confirm Logout': 'تایید خروج',
      'Are you sure you want to log out?': 'واقعا میخوای از حسابت خارج بشی؟',
      'Cancel': 'خیر',
      'Log Out': 'خروج از حساب',
      'Information': 'اطلاعات',
      'Application version': 'نسخه برنامه',
      'Application developer': 'توسعه‌دهنده برنامه',
      'Application on store': 'برنامه در فروشگاه',
      'View on Google Play': 'مشاهده در گوگل پلی',
      'Description': 'توضیحات',
      'No Internet Connection': 'اتصال به اینترنت وجود ندارد',
      'Please check your connection and try again.': 'لطفا اتصال خود را بررسی کرده و دوباره امتحان کنید.',
      'Connected': 'اتصال برقرار شد',
      'You are now connected to the internet!': 'شما اکنون به اینترنت متصل هستید!',
      'Checking internet connection...': 'در حال بررسی اتصال به اینترنت...',
      'Connected to the internet!': 'به اینترنت متصل شد!',
    },
  };
}
