import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'Confirm Logout': 'Confirm Logout',
      'Are you sure you want to log out?': 'Are you sure you want to log out?',
      'Cancel': 'Cancel',
      'Log Out': 'Log Out',
      'Inbox': 'Inbox',
      'Hello': 'Hello',
      'Extras': 'Extras',
      'HOME': 'HOME',
      'Login': 'Login',
      'Acount Center': 'Acount Center',
      'Search': 'Search',
      'Sign up': 'Sign up',
      'username': 'Username',
      'password': 'Password',
      'enter_otp': 'Enter OTP',
      'verify_otp': 'Verify OTP',
      'login_successful': 'Logged in successfully!',
      'otp_invalid': 'Invalid OTP, please try again.',
      'error': 'Error',
      'enter_credentials': 'Please enter your credentials.',
      'invalid_otp': 'Invalid OTP format.',
      'My Cars': 'My Cars',
      'Favorites': 'Favorites',
      'Home': 'Home',
      'Settings': 'Settings',
      'Shop': 'Shop',
      'Map': 'Map',
      'Work': 'Work',
      'Travel': 'Travel',
      'Garage': 'Garage',
      'Contact': 'Contact',
      'Search Page': 'Search Page',
      'Notifications Page': 'Notifications Page',
      'Profile Page': 'Profile Page',
      'Page Not Found': 'Page Not Found',
      'ECU': 'ECU',
      'PARS': 'PARS',
      'Profile': 'Profile',
      'Account Center': 'Account Center',
      'Manage your connected account, add or integrate': 'Manage your connected account, add or integrate',
      'This is the test text from ECUPars': 'This is the test text from ECUPars',
      'This app is improving constantly.': 'This app is improving constantly.',
      'test user': 'Test User',
      'Your Product': 'Your Product',
      'Product info': 'Product Information',
      'Invite Section': 'Invite Section',
      'Your invite code': 'Your Invite Code',
      'About App': 'About App',
      'Share App': 'Share App',
      'Contact Support': 'Contact Support',
      'Account': 'Account',
      'Invitation': 'Invitation',
      'Agreement': 'Agreement',
      'Private Policy': 'Privacy Policy',
      'Ver 0.0.0.1': 'Version 0.0.0.1',
      'Application Theme': 'Application Theme',
      'Light': 'Light',
      'Dark': 'Dark',
      'Application Language': 'Application Language',
      'Language:': 'Language:',
      'Application Preference': 'Application Preference',
      'This section is on development': 'This section is under development',
      'Recommend ECU Pars to friends': 'Recommend ECU Pars to friends',
      'nearby without Internet.': 'nearby without Internet.',
      'QR code': 'QR code',
      'Open URL': 'Open URL',
      'Share Via': 'Share Via',
      'Qr Code': 'Qr Code',
      'URL': 'URL',
      'Facebook': 'Facebook',
      'More': 'More',
      'Logout from your account': 'Logout from your account',
      'Log out': 'Log out',
      'Information': 'Information',
      'Application version': 'Application version',
      'Application developer': 'Application developer',
      'Application on store': 'Application on store',
      'View on Google Play': 'View on Google Play',
      'Description': 'Description',
      'No Internet Connection': 'No Internet Connection',
      'Please check your connection and try again.': 'Please check your connection and try again.',
      'Connected': 'Connected',
      'You are now connected to the internet!': 'You are now connected to the internet!',
      'Checking internet connection...': 'Checking internet connection...',
      'Connected to the internet!': 'Connected to the internet!',
    },
    'fa': {
      'Log out': 'خروج',
      'Logout from your account': 'خروج از حساب کاربری',
      'Inbox': 'اعلانات',
      'Hello': 'سلام',
      'Extras': 'کاربردی',
      'HOME': 'خانه',
      'Login': 'ورود',
      'Search': 'کاوش',
      'Sign up': 'ثبت نام',
      'username': 'نام کاربری',
      'password': 'رمز عبور',
      'enter_otp': 'کد ارسال شده را تایید کنید',
      'verify_otp': 'تایید کد بک بار مصرف',
      'login_successful': 'ورود موفقیت آمیز',
      'otp_invalid': 'کد یکبار مصرف نامعتبر',
      'error': 'خطا',
      'enter_credentials': 'خطا اعتبارسنجی',
      'invalid_otp': 'کد اعتبارسنجی نامعتبر',
      'My Cars': 'ماشین‌های من',
      'Favorites': 'موارد دلخواه',
      'Home': 'خانه',
      'Settings': 'تنظیمات',
      'Shop': 'فروشگاه',
      'Map': 'نقشه',
      'Work': 'کار',
      'Travel': 'سفر',
      'Garage': 'گاراژ',
      'Contact': 'تماس',
      'Search Page': 'صفحه جستجو',
      'Notifications Page': 'صفحه اطلاعیه‌ها',
      'Profile Page': 'صفحه پروفایل',
      'Page Not Found': 'صفحه پیدا نشد',
      'ECU': 'ECU',
      'PARS': 'PARS',
      'Profile': 'پروفایل',
      'Acount Center': 'مرکز حساب',
      'Manage your connected account, add or integrate': 'حساب‌ متصل خود را مدیریت کنید',
      'This is the test text from ECUPars': 'این یک متن آزمایشی از ECUPars است',
      'This app is improving constantly.': 'این برنامه دائما در حال بهبود است.',
      'test user': 'کاربر آزمایشی',
      'Your Product': 'محصول شما',
      'Product info': 'اطلاعات محصول',
      'Invite Section': 'بخش دعوت',
      'Your invite code': 'کد دعوت شما',
      'About App': 'درباره برنامه',
      'Share App': 'اشتراک‌گذاری برنامه',
      'Contact Support': 'پشتیبانی تماس',
      'Account': 'حساب کاربری',
      'Invitation': 'دعوت‌نامه',
      'Agreement': 'توافق‌نامه',
      'Private Policy': 'سیاست حفظ حریم خصوصی',
      'Ver 0.0.0.1': 'نسخه ۰.۰.۰.۱',
      'Application Theme': 'تم برنامه',
      'Light': 'روشن',
      'Dark': 'تاریک',
      'Application Language': 'زبان برنامه',
      'Language:': 'زبان:',
      'Application Preference': 'ترجیح برنامه',
      'This section is on development': 'این بخش در حال توسعه است',
      'Recommend ECU Pars to friends': 'ECU Pars را به دوستانتان معرفی کنید',
      'nearby without Internet.': 'بدون نیاز به اینترنت در نزدیکی.',
      'QR code': 'کد QR',
      'Open URL': 'باز کردن لینک',
      'Share Via': 'اشتراک‌گذاری از طریق',
      'Qr Code': 'کد QR',
      'URL': 'لینک',
      'Facebook': 'فیس‌بوک',
      'More': 'بیشتر',
      'Confirm Logout': 'تایید خروج',
      'Are you sure you want to log out?': 'واقعا میخوای از حسابت خارج بشی؟',
      'Cancel': 'خیر',
      'Log Out': 'خروج از حساب',
      'Information': 'اطلاعات',
      'Application version': 'نسخه برنامه',
      'Application developer': 'توسعه‌دهنده برنامه',
      'Application on store': 'برنامه در فروشگاه',
      'View on Google Play': 'مشاهده در گوگل پلی',
      'Description': 'توضیحات',
      'No Internet Connection': 'اتصال به اینترنت وجود ندارد',
      'Please check your connection and try again.': 'لطفا اتصال خود را بررسی کرده و دوباره امتحان کنید.',
      'Connected': 'اتصال برقرار شد',
      'You are now connected to the internet!': 'شما اکنون به اینترنت متصل هستید!',
      'Checking internet connection...': 'در حال بررسی اتصال به اینترنت...',
      'Connected to the internet!': 'به اینترنت متصل شد!',
    },
  };
}
